# Generated by Django 2.0.7 on 2019-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.UUIDField()),
                ('st_time', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '计划时间表',
                'verbose_name_plural': '计划时间表',
                'ordering': ['pk'],
            },
        ),
    ]
