# Generated by Django 2.0.7 on 2019-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletime',
            name='st_type',
            field=models.ManyToManyField(to='schedule.ScheduleType', verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='st_id',
            field=models.UUIDField(verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='st_time',
            field=models.DateField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='stp_id',
            field=models.UUIDField(verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='scheduletype',
            name='stp_type',
            field=models.CharField(max_length=200, verbose_name='类型'),
        ),
    ]
